### PR TITLE
patch to solve the Google Analytics issue

### PR DESCRIPTION
**Pull request by ocefpaf**
@bollwyvl and @jorisvandenbossche are you OK with this patch? It is almost merged upstream but many projects require a solution for this ASAP. If not feel free to just close it and we'll wait for the new release.

### CODE REVIEW

**Comment by ocefpaf** [comment]
The failing tests are:

```
test_sidebars_captions
test_sidebars_nested_page
test_sidebars_single
test_sidebars_level2
test_new_google_analytics_id
test_old_google_analytics_id
```

They all need to change upstream too to accommodate this change. Would it be OK to disable them or skip all tests?

**Comment by ocefpaf** [comment]
@bollwyvl and @jorisvandenbossche I understand that patching and turning off the tests is... controversial to say the least :-)
But please take a look and if you agree merge this one until we can fix it upstream. Many site don't have proper statistics and some require that to assess engagement and seek out funds.

**Comment by jorisvandenbossche** [comment]
Sorry for the slow reply here / on the issue. 

The tests are failing because of a new sphinx version that changed output (this is fixed in the master version of the theme), and because the PR still needed to fix its own tests.

I am now looking at the PR, so maybe we can also still do a quick actual release. 

@ocefpaf just for my understanding, why is this urgent now (the PR is adding the new-style gtag as a new feature, but the old style is already working. Or did something start failing here?)

**Comment by ocefpaf** [comment]
> why is this urgent now (the PR is adding the new-style gtag as a new feature, but the old style is already working. Or did something start failing here?)

I don't know all the details but I guess the old style gtag is not an option. If you are looking at the PR upstream we can afford to wait. I'll also ask folks who want this if they can use the old style tag.

**Comment by jorisvandenbossche** [comment]
No problem in doing a quick release to be clear. I just don't really understand the "why" :)

**Comment by ocefpaf** [comment]
Solved upstream. Thanks @jorisvandenbossche!

**Pull request closed without merging**
