### PR TITLE
Update to `0.14.0` (incl. Python version upgrade, etc.)

### PR DESCRIPTION
**Pull request by michaelweinold**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Release notes: https://github.com/pydata/pydata-sphinx-theme/releases
This supersedes the failed auto-update PR:

 - https://github.com/conda-forge/pydata-sphinx-theme-feedstock/pull/40

### CODE REVIEW

**Comment by michaelweinold** [comment]
@conda-forge-admin, please rerender

**Comment by michaelweinold** [comment]
@conda-forge/core, this is ready for review.

**Comment by jaimergp** [comment]
cc @conda-forge/pydata-sphinx-theme

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
Thanks! I pushed a few patches and removed the auto-auto-merge (I feel like it seldom works out well for this package), and have marked it to manual-auto-merge, so builds should be up soon. Thanks, and welcome to the team :heart:

**Comment by michaelweinold** [comment]
Thank you very much - glad to be able to contribute!

**Pull request merged**
